script: "bundle exec rake appraisal:integration test"
rvm:
  - 1.8.6
  - 1.8.7
  - 1.9.1
  - 1.9.2
env:
  - INTEGRATION=default
  - INTEGRATION=active_model
  - INTEGRATION=active_record
  - INTEGRATION=data_mapper
  - INTEGRATION=mongoid
  - INTEGRATION=mongo_mapper
  - INTEGRATION=sequel
