script: "bundle exec rake appraisal:integration test"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby
env:
  - INTEGRATION=default TRAVIS=true
  - INTEGRATION=active_model TRAVIS=true
  - INTEGRATION=active_record TRAVIS=true
  - INTEGRATION=data_mapper TRAVIS=true
  - INTEGRATION=mongoid TRAVIS=true
  - INTEGRATION=mongo_mapper TRAVIS=true
  - INTEGRATION=sequel TRAVIS=true
notifications:
  disabled: true
matrix:
  exclusions:
    - rvm: jruby
      env: INTEGRATION=active_model TRAVIS=true
    - rvm: jruby
      env: INTEGRATION=active_record TRAVIS=true
    - rvm: jruby
      env: INTEGRATION=data_mapper TRAVIS=true
    - rvm: jruby
      env: INTEGRATION=mongoid TRAVIS=true
    - rvm: jruby
      env: INTEGRATION=mongo_mapper TRAVIS=true
    - rvm: jruby
      env: INTEGRATION=sequel TRAVIS=true
